app:

  event-hub:
    connection-string: ${EVCS}
    consumer-group: ${CG}
    batch-size: 10000
    prefetch-count: 500

    storage:
      connection-string: ${SCS}
      container-name: ${SCN}