app:

  event-hub:
    partition-count: ${EVPC}
    connection-string: ${EVCS}
    consumer:
      consumer-group: ${CG}
      batch-size: 1998
      prefetch-count: 1999

    storage:
      connection-string: ${EVSCS}
      container-name: ${EVSCN}

    producer:
      fixed-rate: 1

spring:
  banner:
    location: classpath:/awesome.banner